In [290]:
import numpy as np
import pandas as pd
from io import StringIO
import numpy as np
import matplotlib.pyplot as plt

In [103]:
# Learn Numpy

# Create Numpy arrays

mat = np.zeros((3,3), dtype=int)

mat = np.ones((3, 3), dtype=int)

mat = np.arange(10, 25, 5)

mat = np.linspace(1, 10, 9, dtype=int)

mat = np.identity(3, dtype=int)
# help(np.linspace)

# print mat

In [104]:
# Load Numpy Arrays from text file

d = StringIO(u'M 21 72\nF 35 58')
res = np.loadtxt(d, dtype={'names': ('gender', 'age', 'weight'),
                     'formats': ('S1', 'i4', 'f4')})
# print res

# Import data
x, y, z = np.loadtxt('data.txt',
                    skiprows=1,
                    unpack=True)
# print x
# print y
# print z

# Load Numpy Array from text file using genfromtxt method

my_array2 = np.genfromtxt('data2.txt',
                      skip_header=1,
                      filling_values=1)

# print my_array2

s = StringIO(u"1,1.3,abcde")
data = np.genfromtxt(s, dtype=[('myinddt','i8'),('myfloat','f8'),
                               ('mystring','S5')], delimiter=",")

s.seek(0)
data = np.genfromtxt(s, dtype=None, delimiter=",")
# print data

# Save array to file

x = np.arange(10,25,5)
np.savetxt('test.out', x, delimiter=',', fmt='%d')


In [135]:
# Insepct Numpy Arrays

my_array = np.array([[1, 2, 5, 7], [3, 6, 4, 8]], dtype=np.int8)

# Print the number of `my_array`'s dimensions
print(my_array.ndim)

# Print the number of `my_array`'s elements
print(my_array.size)

# Print information about `my_array`'s memory layout
print(my_array.flags)

# Print the length of one array element in bytes
print(my_array.itemsize)

# Print the total consumed bytes by `my_array`'s elements
print(my_array.nbytes)

# Type of an array
print(my_array.dtype)

# change type of an array
print(my_array.astype(float))
print(my_array.dtype)


2
8
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
1
8
int8
[[ 1.  2.  5.  7.]
 [ 3.  6.  4.  8.]]
int8


In [177]:
# Numpy Array broadcasting

# Initialize `x`
x = np.ones((2,3))

# Check shape of `x`
print(x)

# Initialize `y`
y = np.array([[1, 2, 3],[4, 5, 6]])

# Check shape of `y`
print(y.shape)

# Add `x` and `y`
x + y

# Subtract two arrays
z = np.array([1, 2, 3]) # with different shape (3,)

# Check shape of `z`
print(z.shape)
x - z
print np.random.random((5,1,4))

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
(2, 3)
(3,)
[[[ 0.37364355  0.67762829  0.12617186  0.96695303]]

 [[ 0.35830344  0.67085542  0.91164594  0.28416447]]

 [[ 0.04199323  0.27668971  0.06170807  0.83333238]]

 [[ 0.79511239  0.50302279  0.33533656  0.49506084]]

 [[ 0.01697272  0.02205323  0.67533832  0.37298891]]]


In [255]:
# Index and Slicing

my_2d_array = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)
# or 

my_2d_array = np.arange(1,7).reshape(2, 3)


# Select the element at row 1 column 2
# print(my_2d_array[1,2])

# Select Items at index 0
# print(my_2d_array[0:1])

# Select Items at index 0 and 1
# print(my_2d_array[0:2])

# Select the element at row 0 and 1 and column 1
# print(my_2d_array[0:2,1]) # 6

my_3d_array = np.arange(90) # Create an array of 90 elements
my_3d_array = my_3d_array.reshape(9, 2, 5) # generate 9 arrays of 2x5 (2 rows 5 cols)

# Select the element at row 1, column 2 of 3 row 
# print(my_3d_array[3,1,2])

# Select Items at 0th rows, then select element at row 1 col 2
# print my_3d_array[0][1][2]

# Try out a simple example
# print(my_2d_array[my_2d_array<2])

# Specify a condition
bigger_than_3 = (my_3d_array >= 3)

# Use the condition to index our 3d array
# print(my_3d_array[bigger_than_3])

my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]]])

In [257]:
# Select elements at (1,0), (0,1), (1,2) and (0,0)
print(my_2d_array[[1, 0, 1, 0],[0, 1, 2, 0]])

# Select a subset of the rows and columns
# print(my_2d_array[[1, 0, 1, 0]][:,[0,1,2,0]])

[4 2 6 1]


In [259]:
# Help functions `np.lookfor()` and `np.info()`

# Look up info on `mean` with `np.lookfor()` 
# print(np.lookfor("mean"))

# Get info on data types with `np.info()`
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [260]:
# Transpose Numpy Arrays

# Print `my_2d_array`
print(my_2d_array)

# Transpose `my_2d_array`
print(np.transpose(my_2d_array))

# Or use `T` to transpose `my_2d_array`
print(my_2d_array.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [280]:
# Append to Numpy Array

my_array = np.arange(1, 6)
# Append a 1D array to your `my_array`
new_array = np.append(my_array, [7, 8, 9, 10])

# Print `new_array`
print(new_array)

print(my_2d_array)

# Append an extra column to your `my_2d_array`
new_2d_array = np.append(my_2d_array, [[7], [8]], axis=1)

# Print `new_2d_array`
print(new_2d_array)



# Insert And Delete Array Elements - `np.insert(arr, index, element), np.delete(arr, [index])

# ones = np.ones(3)
# print(ones)

# # # Insert element 5 at index 2
# ones = np.insert(ones, 1, 5)
# print(ones)

# # Remove element from index 2
# ones = np.delete(ones, [1])

# print (ones)

[ 1  2  3  4  5  7  8  9 10]
[[1 2 3]
 [4 5 6]]
[[1 2 3 7]
 [4 5 6 8]]


In [303]:
# Visualize Numpy Arrays

# Initialize your array
my_3d_array = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [9,10,11,12]]], dtype=np.int64)
# print my_3d_array
# print my_3d_array.shape

# Pass the array to `np.histogram()`
# print(np.histogram(my_3d_array))

# Specify the number of bins
# print(np.histogram(my_3d_array, bins=range(0,13)))

# Construct the histogram with a flattened 3d array and a range of bins
plt.hist(my_3d_array.ravel(), bins=range(0,13))

# Add a title to the plot
plt.title('Frequency of My 3D Array Elements')

# Show the plot
# plt.show()
my_3d_array = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [9,10,11,12]]], dtype=np.int64)
my_3d_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]]])